site_name: Swarms Torch Package Docs
plugins:
  - glightbox
  - search
copyright: "&copy; APAC Corp, Inc."
extra_css:
  - docs/assets/css/extra.css
extra:
  # analytics:
  #   provider: google
  #   property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/solid/house
      link: assets/img/ZetaLogoIcon.png
    - icon: fontawesome/brands/discord
      link: https://discord.gg/qUtxnK2NMf
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/Zeta/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/Zeta/
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/img/ZetaLogoIcon.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'custom'
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
    font:
      text: Roboto
      code: Roboto Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - tables
  - def_list
  - footnotes


nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
- Swarms:
    - Overview: "swarms/index.md"
    - swarms_torch:
      - ParticleSwarmOptimization: "swarms/pso.md"
      - AntColonyOptimization: "swarms/aco.md"
      - 
- Examples:
    - Overview: "examples/index.md"
    - FlashAttention: "examples/nn/attentions/flash.md"
    