docs_dir: '.'  # replace with the correct path if your documentation files are not in the same directory as mkdocs.yml
site_name: Swarm Model Architectures
# site_url: https://docs.swarms.world
site_author: Swarms
site_description: Swarming algorithms like PSO, Ant Colony, Sakana, and more in PyTorch 😊
repo_name: kyegomez/swarms-torch
repo_url: https://github.com/kyegomez/swarms-pytorch
edit_uri: https://github.com/kyegomez/swarms-pytorch/tree/main/docs
copyright: TGSC Corp 2024. All rights reserved.

plugins:
  # - glightbox
  - search
  - git-authors
  - mkdocs-jupyter:
        kernel_name: python3
        execute: false
        include_source: True
        include_requirejs: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            parameter_headings: true
            paths: [supervision]
            load_external_modules: true
            allow_inspection: true
            show_bases: true
            group_by_category: true
            docstring_style: google
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_category_heading: true
          domains: [std, py]
  - git-committers:
      repository: kyegomez/swarms
      branch: master
      # token: !ENV ["GITHUB_TOKEN"]
  - git-revision-date-localized:
      enable_creation_date: true
extra_css:
  - assets/css/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/KyeGomezB
    - icon: fontawesome/brands/github
      link: https://github.com/kyegomez/swarms-pytorch
    - icon: fontawesome/brands/twitter
      link: https://x.com/swarms_corp
    - icon: fontawesome/brands/discord
      link: https://discord.com/servers/agora-999382051935506503

  analytics:
    provider: google
    property: G-MPE9C65596

theme:
    name: material
    custom_dir: overrides
    logo: assets/img/swarms-logo.png
    palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - announce.dismiss
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - Overview: "swarms/index.md"
    - Purpose: "swarms/purpose.md"
    - swarms_torch:
      - ParticleSwarmOptimization: "swarms/pso.md"
      - AntColonyOptimization: "swarms/aco.md"
      - QueenBeeGa: "swarms/qb.md"
      - SpiralOptimization: "swarms/so.md"
      - FireflyOptimizer: "swarms/firefly.md"
